image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: aufs

before_script:
  - docker info

LATEST:
  stage: build
  script:
    - docker build -t meteor .
    - docker tag meteor larsvh/meteor:latest
    - docker images
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker -D push larsvh/meteor
  only:
    - master

STANDALONE:
  stage: build
  script:
    - docker build -t meteor .
    - docker tag meteor larsvh/meteor:standalone
    - docker images
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker -D push larsvh/meteor
  only:
    - standalone

v1.2.1:
  stage: build
  script:
    - docker build -t meteor .
    - docker tag meteor larsvh/meteor:1.2.1
    - docker images
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push larsvh/meteor
  only:
    - v1.2.1
