image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: aufs

before_script:
  - docker info

after_script:
  - docker login -u $DH_USER -p $DH_PASS hub.docker.com
  - docker images
  - docker push larsvh/meteor

LATEST:
  stage: build
  script:
    - docker build -t meteor .
    - docker tag meteor larsvh/meteor:latest
  only:
    - master

v1.2.1:
  stage: build
  script:
    - docker build -t meteor .
    - docker tag meteor larsvh/meteor:1.2.1
  only:
    - v1.2.1
