image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: aufs

before_script:
  - docker info

LATEST:
  stage: build
  script:
    - docker build -t meteor .
    - docker tag meteor larsvh/meteor:latest
  artifacts:
    paths:
      - /var/lib/docker/
  only:
    - master

v1.2.1:
  stage: build
  script:
    - docker build -t meteor .
    - docker tag meteor larsvh/meteor:1.2.1
  artifacts:
    paths:
      - /var/lib/docker/
  only:
    - v1.2.1

PUBLISH:
  stage: deploy
  script:
    - docker login -u $DH_USER -p $DH_PASS hub.docker.com
    - docker images
    - docker push larsvh/meteor
