image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: aufs

before_script:
  - docker info

LATEST:
  stage: build
  script:
    - docker build -t meteor .
    - docker tag meteor larsvh/meteor:latest
    - docker images
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker -D push larsvh/meteor
    - apk add git
    - git push --mirror https://$GITHUB_USER:$GITHUB_TOKEN@github.com/larsvanherk/docker-meteor.git
  only:
    - master

v1.2.1:
  stage: build
  script:
    - docker build -t meteor .
    - docker tag meteor larsvh/meteor:1.2.1
    - docker images
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push larsvh/meteor
  only:
    - v1.2.1
