---
jobs:
- name: LATEST
  public: true
  serial_groups: ['meteor-image']
  plan:
  - get: git-repo
    trigger: true
  - put: image-latest
    params:
      build: git-repo/latest

- name: STANDALONE
  public: true
  serial_groups: ['meteor-image']
  plan:
  - get: git-repo
    trigger: true
  - put: image-standalone
    params:
      build: git-repo/standalone

- name: v1.2.1
  public: true
  serial_groups: ['meteor-image']
  plan:
  - get: git-repo
    trigger: true
  - put: image-v1.2.1
    params:
      build: git-repo/v1.2.1

resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/larsvanherk/docker-meteor
    branch: master
    private_key: {{github-private-key}}

- name: image-latest
  type: docker-image
  source:
    username: {{DOCKER_USER}}
    password: {{DOCKER_PASSWORD}}
    repository: larsvh/meteor
    tag: latest

- name: image-standalone
  type: docker-image
  source:
    username: {{DOCKER_USER}}
    password: {{DOCKER_PASSWORD}}
    repository: larsvh/meteor
    tag: standalone

- name: image-v1.2.1
  type: docker-image
  source:
    username: {{DOCKER_USER}}
    password: {{DOCKER_PASSWORD}}
    repository: larsvh/meteor
    tag: v1.2.1
