---
jobs:
- name: docker-meteor-latest
  public: true
  serial: true
  plan:
  - get: git-repo-latest
    trigger: true
  - put: docker-image
    params:
      build: git-repo-latest/latest

resources:
- name: git-repo-latest
  type: git
  source:
    uri: https://github.com/larsvanherk/docker-meteor
    branch: master
    private_key: {{github-private-key}}

- name: docker-image
  type: docker-image
  source:
    username: {{DOCKER_USER}}
    password: {{DOCKER_PASSWORD}}
    repository: larsvh/meteor
    tag: latest
